name: TUF-on-CI online signing

permissions: {}

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  push:
    branches: [ main ]
    paths: ['metadata/**']
  workflow_dispatch:

jobs:
  online-sign:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write' # for commiting snapshot/timestamp changes
      actions: 'write' # for dispatching publish workflow

    steps:
      - id: online-sign
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
        uses: theupdateframework/tuf-on-ci/actions/online-sign@df797d1d59a37c90baa15a84ccde6fd8987fa38a
